services:
  rstudio:
    build:
      context: .
      dockerfile: docker/rstudio/Dockerfile
    image: rtatools/rstudio
    container_name: rtatools-rstudio
    environment:
      TZ: Asia/Tokyo
      DISABLE_AUTH: true
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/rtatools
