services:
  rstudio:
    build:
      context: .
      dockerfile: docker/rstudio/Dockerfile
    image: rtatools/rstudio
    container_name: rtatools-rstudio
    environment:
      TZ: Asia/Tokyo
      DISABLE_AUTH: true
    ports:
      - "18787:8787"
    volumes:
      - .:/home/rstudio/rtatools
  database:
    image: postgis/postgis
    container_name: rtatools-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: traffic_accident_database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
